### ISSUE TITLE
About Fire Walker

### ISSUE THREAD

**Issue by Start-Buling** [aleganza/Plenty-Of-Armor#7]
hello,
I noticed that this mod includes a buff called 'Fire Walker'. II thought it might be like 'Frost Walker', temporarily generating obsidian or other blocks while walking on lava, just like Frost Walker temporarily generating ice blocks under my feet.However, when I wore the Stardusite armor set and walked on lava, it generated Blackstone beneath my feet. This Blackstone seems to be generated permanently. I'm not sure if this is a bug or if you intentionally designed it this way. So, I wanted to ask you about it.
![XQKZZ7OV2O)EI$ ASNQ}D%Y](https://github.com/aleganza/Plenty-Of-Armors/assets/58358555/f03b45c9-c191-4a1f-9865-62351f6ff9c8)

**Comment by aleganza** [comment]
Hi! Actually it's not a bug but meant to be so. The Frost Walker effect spawns a particular type of ice block (frosted ice) which can't be obtained in vanilla and its only usage comes from the enchantment. It's different from other blocks because it has his 3 own melting states so it can break itself after its placement from the enchantment. To make Fire Walker identical to Frost Walker the block it generates should be temporary as you said, but if so we had to create a new custom block (similar to blackstone or obsidian) with its own "melting states" so it could break automatically after its placement from the effect. Since it seemed like much more work to do only for a custom effect, we decided to leave it as it is, like many other effects we could'nt add because much harder to make. Maybe in the future with an "Effect Update" we will enhance this effect as we know it would look better if the blocks generated were temporary.

**Comment by Start-Buling** [comment]
Thank you for your reply, I understand. I look forward to you adding more interesting content to this mod. I will promote it for you and experience your mod in a timely manner. Once again, thank you for being willing to provide such detailed answers to my questions.

**Comment by aleganza** [comment]
You are welcome! Enjoy the mod!
